service: the-camp-letter

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-2
  stage: p
  memorySize: 128
  timeout: 300

functions:
  hello:
    handler: handler.send_letter
    events:
      - schedule:
          rate: cron(0 3 * * ? *)
          enabled: true
          description: 'TheCampLetter'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: true